# -*- coding: utf-8 -*-

{
    'name': 'Product Brand',
    'author': 'abhilash',
    'version': '16.0.1.0.0',
    'category': 'Technicals',
    'depends': ['base','purchase','sale_management','contacts','mail','hr'],
    'description': "Product Brand",
    'data': ['security/ir.model.access.csv',
             'security/security_access.xml',
             'security/brand_access.xml',
             'security/account_move_access.xml',
             'data/customer_number_views.xml',
             'views/product_views.xml',
             'views/food_products_views.xml',
             'views/food_items_views.xml',
             'views/product_brand_views.xml',
             'views/contact_views.xml',
             'views/sale_line_views.xml',
             'views/purchase_line.xml',
             'views/product_email_views.xml',
             'data/stock_views.xml',
             'views/contact_selection_views.xml',
             'views/vendor_partner_views.xml',
             'wizard/wizard_views.xml',
             'wizard/template_wizard_view.xml',
             'report/sale_print.xml',
             'views/material_list_views.xml',
             'views/material_product_views.xml',
             'views/cloth_list_views.xml',
             'views/cloth_product_views.xml',
             'views/invoice_line_views.xml',
             'report/invoice_print.xml',
             'views/brand_sale_views.xml',
             'views/vehicle_acc_list_views.xml',
             'views/vehicle_acc_product_views.xml',
             'views/employee_code_views.xml',
             'views/school_acc_list_views.xml',
             'views/school_accessories_views.xml',
             'views/food_product_menus.xml',
             ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
